# Generated by Django 4.1.9 on 2023-05-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="students",
            new_name="student_model",
        ),
    ]
